import type { Metadata } from "next";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: Promise<{ locale: string }>; // `params` is a Promise
}

export default async function RootLayout({
  children,
  params,
}: RootLayoutProps) {
  // Resolve the `params` Promise
  const resolvedParams = await params;
  const { locale } = resolvedParams;

  // Fetch messages for the resolved locale
  const messages = await getMessages({ locale });

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages} locale={locale}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
